version: '3.4'

services:
  factories.webapi.bll:
    image: ${DOCKER_REGISTRY-}factorieswebapibll
    build:
      context: .
      dockerfile: src/Factories.WebApi.BLL/Dockerfile
    depends_on:
      - postgres-container
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-container;Port=5432;Database=postgres;Username=postgres;Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__UsersConnection=Host=postgres-container;Port=5432;Database=postgres;Username=postgres;Password=${POSTGRES_PASSWORD}
  postgres-container:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
